var test = require('./app/test');
var tap = require('tap');

tap.test('Test A', test('test/A'));
tap.test('Test B_ns', test('test/B_ns'));
tap.test('Test B_ds', test('test/B_ds'));
tap.test('Test B_rs', test('test/B_rs'));
tap.test('Test B_ws', test('test/B_ws'));
tap.test('Test C', test('test/C'));
tap.test('Test D', test('test/D'));
tap.test('Test E_ns', test('test/E_ns'));
tap.test('Test E_ds', test('test/E_ds'));
tap.test('Test E_rs', test('test/E_rs'));
tap.test('Test E_ws', test('test/E_ws'));
tap.test('Test F', test('test/F'));
tap.test('Test G_ns', test('test/G_ns'));
tap.test('Test G_ds', test('test/G_ds'));
tap.test('Test G_rs', test('test/G_rs'));
tap.test('Test G_ws', test('test/G_ws'));
tap.test('Test H_ns', test('test/H_ns'));
tap.test('Test H_ds', test('test/H_ds'));
tap.test('Test H_rs', test('test/H_rs'));
tap.test('Test H_ws', test('test/H_ws'));
tap.test('Test I_ns', test('test/I_ns'));
tap.test('Test I_ds', test('test/I_ds'));
tap.test('Test I_rs', test('test/I_rs'));
tap.test('Test I_ws', test('test/I_ws'));
tap.test('Test J', test('test/J'));
tap.test('Test K', test('test/K'));
tap.test('Test L_ns', test('test/L_ns'));
tap.test('Test L_ds', test('test/L_ds'));
tap.test('Test L_rs', test('test/L_rs'));
tap.test('Test L_ws', test('test/L_ws'));
